名前: ルームポスターボット

on:
  workflow_dispatch:          # 手動実行
  schedule:                   # 毎日 07:05/15:00/22:30 に自動実行
    - cron:  '5 22 * * *'
    - cron:  '0 6 * * *'
    - cron:  '30 13 * * *'

jobs:
  post:
    runs-on: [self-hosted, Windows, X64]   # ← ここを **必ず** 修正
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python をセットアップする
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 依存ライブラリをインストール
        run: pip install -r requirements.txt

      - name: 自動投稿スクリプトを実行
        env:
          RAKUTEN_ID:   ${{ secrets.RAKUTEN_ID }}
          RAKUTEN_PASS: ${{ secrets.RAKUTEN_PASS }}
        run: |
          python room_poster.py --no-headless
