name: ルームポスターボット

on:
  workflow_dispatch:        # 手動
  schedule:
    - cron: '5 22 * * *'    # 例) 毎日 07:05JST

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python 3.11 セットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 依存ライブラリをインストール
        run: pip install -r requirements.txt

      - name: 自動投稿スクリプトを実行
        env:
          RAKUTEN_ID:   ${{ secrets.RAKUTEN_ID }}
          RAKUTEN_PASS: ${{ secrets.RAKUTEN_PASS }}
        run: python room_poster.py
